db:
  image: postgres
  ports:
    - "5432"

redis:
  image: redis
  ports:
    - "6379"

sidekiq:
  build: .
  command: bash -l -c 'rvm use ruby-2.2.3 && bundle exec sidekiq'
  links:
    - db
    - redis

web:
  build: .
  command: bash -l -c 'rvm use ruby-2.2.3 && bundle exec rails s -b 0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
    - redis
